name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.3
  http: ^1.2.2          # Check for newer versions if needed
  intl: ^0.19.0          # Good for internationalization
  bson: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0   # Good linting package for Flutter projects

flutter:
  uses-material-design: true
